# Generated by Django 4.1 on 2022-08-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
